version: '3.8'
services:
  ms_users_db:
    image: mysql:latest
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 512M
    container_name: ms_email_db
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_email
  rabbitmq:
      image: rabbitmq:4.0.2-management-alpine
      container_name: email-queue
      ports:
        - 5672:5672
        - 15672:15672
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest

