version: '3.8'
services:
  ms_users_db:
    image: mysql:latest
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 512M
    container_name: ms_email_db
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_email